# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_data', '0001_firstmigrations'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricehistory',
            name='market_cap',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
